#!/bin/sh

mount -a

# added by huangqingjia for sysfs
mount -t sysfs /sys /sys
# ended add

/bin/mkdir -m 0777 -p /var/lock
/bin/mkdir -m 0777 -p /var/log
/bin/mkdir -m 0777 -p /var/run
/bin/mkdir -m 0777 -p /var/tmp
/bin/mkdir -m 0777 -p /var/Wireless/RT2860AP
/bin/mkdir -m 0777 -p /var/tmp/wsc_upnp/
/bin/mkdir -m 0777 -p /var/tmp/wsc_upnp_5G/

#for tpapp dropbear
/bin/mkdir -m 0777 -p /var/tmp/dropbear

#for the dirs of samba and ntfs-3g, zjj, 20111129
/bin/mkdir -m 0777 -p /var/usbdisk
/bin/mkdir -m 0777 -p /var/dev
/bin/mkdir -m 0777 -p /var/samba/lib
/bin/mkdir -m 0777 -p /var/samba/private
/bin/mkdir -m 0777 -p /var/samba/var/locks
cp -p /etc/passwd.bak /var/passwd
/bin/mkdir -m 0777 -p /var/3G
#end by zjj

#for the dirs of vdsl in 9980, wzy, 20130315
/bin/mkdir -m 0777 -p /var/xdsl_changeover
#end by wzy

#added by CCy for Vpn, 07Jul2015
/bin/mkdir -m 0777 -p /var/easy-rsa
/bin/mkdir -m 0777 -p /var/easy-rsa/keys
/bin/mkdir -m 0777 -p /var/openvpn

/bin/mkdir -m 0777 -p /var/pptpd
#add ended

#for https certificate
/bin/mkdir -m 0777 -p /var/https

echo 5120 > /proc/sys/vm/min_free_kbytes
echo 2 > /proc/sys/vm/overcommit_memory
echo 95 > /proc/sys/vm/overcommit_ratio
echo 250 > /proc/sys/vm/lowmem_reserve_ratio
echo 2 > /proc/sys/vm/dirty_background_ratio
echo 250 > /proc/sys/vm/dirty_writeback_centisecs
echo 10 > /proc/sys/vm/dirty_ratio
echo 16384 > /proc/sys/vm/max_map_count
echo 2 > /proc/sys/vm/page-cluster
echo 90 > /proc/sys/vm/swappiness

ulimit -s 2048

insmod /lib/modules/kmdir/kernel/drivers/scsi/scsi_mod.ko
insmod /lib/modules/kmdir/kernel/drivers/scsi/scsi_wait_scan.ko
insmod /lib/modules/kmdir/kernel/drivers/scsi/sd_mod.ko
insmod /lib/modules/kmdir/kernel/drivers/usb/core/usbcore.ko
insmod /lib/modules/kmdir/kernel/drivers/usb/host/mtk_xhci/xhci-hcd.ko
insmod /lib/modules/kmdir/kernel/drivers/usb/storage/usb-storage.ko

#add by Zhao Mengqing, 2016-4-2
insmod /lib/modules/module_sel.ko
#insmod /lib/modules/tcsmux.ko
#insmod /lib/modules/tcportbind.ko
#insmod /lib/modules/tcvlantag.ko
insmod /lib/modules/tcledctrl.ko
insmod /lib/modules/tccicmd.ko
#insmod /lib/modules/sif.ko
#insmod /lib/modules/crypto_k.ko
insmod /lib/modules/wlan_ratelimit.ko
insmod /lib/modules/fe_core.ko
insmod /lib/modules/qdma_lan.ko
insmod /lib/modules/eth.ko
insmod /lib/modules/eth_ephy.ko
#insmod /lib/modules/igmpsnoop.ko
insmod /lib/modules/dying_gasp.ko

qdmamgr_lan set rxratelimit config Enable packet
qdmamgr_lan set rxratelimit value 0 60000
qdmamgr_lan set rxratelimit value 1 1000000

insmod /lib/modules/qdma_wan.ko
qdmamgr_wan set rxratelimit config Enable packet
qdmamgr_wan set rxratelimit value 0 60000
qdmamgr_wan set rxratelimit value 1 1000000

ifconfig eth0 up

ifconfig lo up

echo 8192 > /proc/net/skbmgr_driver_max_skb
echo 8192 > /proc/net/skbmgr_limit
echo 4096 > /proc/net/skbmgr_4k_limit 

echo 1 > /proc/sys/net/ipv4/ip_forward
echo 1 > /proc/sys/net/ipv4/tcp_syncookies
#echo 5120 > /proc/sys/net/nf_conntrack_max
echo 4096 > /proc/sys/net/netfilter/nf_conntrack_expect_max
echo 6000 > /proc/sys/net/ipv6/neigh/default/gc_stale_time
echo 1 >/proc/sys/net/ipv6/conf/all/forwarding
echo 30 > /proc/sys/net/unix/max_dgram_qlen
echo 3 > /proc/sys/net/netfilter/nf_conntrack_icmp_timeout 
echo 0 > /proc/sys/net/ipv4/conf/default/accept_source_route
echo 0 > /proc/sys/net/ipv4/conf/all/accept_source_route

echo 8 >/proc/irq/22/smp_affinity
echo 3 > /proc/sys/vm/drop_caches
#end by Zhao Mengqing


#for 3g-dongle, add by zjj, 20120521
mount -t usbfs usbfs /proc/bus/usb/

#netfilter modules load
insmod /lib/modules/kmdir/kernel/net/netfilter/nf_conntrack_proto_gre.ko
insmod /lib/modules/kmdir/kernel/net/netfilter/nf_conntrack_pptp.ko
insmod /lib/modules/ipt_STAT.ko
insmod /lib/modules/tp_domain.ko lan_domain=tplinkmodem.net

telnetd
cmmsyslogd & 

#Add By YuChuwei
echo "MTK DSP support"
echo 3 > /proc/sys/vm/drop_caches
 
insmod /lib/modules/sys_mod.ko
insmod /lib/modules/DSPCore.ko
insmod /lib/modules/pcm1.ko
insmod /lib/modules/lec.ko
insmod /lib/modules/spi.ko
insmod /lib/modules/slic3.ko type=ZSI
insmod /lib/modules/fxs3.ko slic1=le9642 slic2=le9642
insmod /lib/modules/ksocket.ko
insmod /lib/modules/ortp.ko
insmod /lib/modules/acodec_x.ko
insmod /lib/modules/foip.ko
insmod /lib/modules/ovdsp.ko
insmod /lib/modules/pcmDump.ko
 
taskset -p 0x8 `pidof ORTP_TASK`
taskset -p 0x8 `pidof fxs_task`
taskset -p 0x8 `pidof DSPProc`
taskset -p 0x8 `pidof DspDlTask`
taskset -p 0x8 `pidof DspUlTask`
taskset -p 0x8 `pidof cid_task`
 
echo 8 > /proc/irq/12/smp_affinity
#CPU3 is only for VOIP, wangyang 29Jun16
echo 7 > /proc/irq/22/smp_affinity
#echo 3 > /proc/irq/7/smp_affinity

voip_server &
#End Add

insmod /lib/modules/pwm.ko
echo 1 > /proc/tc3162/pwm_start

cos & 
ifconfig br0 192.168.1.1 up

#while true;do
#echo 3 > /proc/sys/vm/drop_caches
#sleep 1
#done &

#sleep 5
#echo "Klog Module Starting..."
#klogd &

#add by hqj, initialize usb
echo "active 19 1" > /proc/tc3162/gpio_output
echo "active 20 1" > /proc/tc3162/gpio_output
#endif

echo "sys modifybit bfb50f80 17 0">/proc/tc3162/tcci_cmd

#echo "WLAN RATELIMIT"
#echo set q_update_token_interval 1400 >/proc/tc3162/wlan_ratelimit_config
#echo ra0 rx 300000 >/proc/tc3162/wlan_ssid_ratelimit
#echo ra0 tx 300000 >/proc/tc3162/wlan_ssid_ratelimit
#echo rai0 rx 1000000 >/proc/tc3162/wlan_ssid_ratelimit
#echo rai0 tx 1000000 >/proc/tc3162/wlan_ssid_ratelimit